apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: task-manager
  name: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: task-manager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: task-manager
    spec:
      containers:
        - image: gargi08092000/task-manager-2
          livenessProbe:
            exec:
              command:
                - curl --fail http://localhost:4200|| exit 0
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: task-manager
          ports:
            - containerPort: 4200
          resources: {}
      restartPolicy: Always
status: {}
